FROM osrf/ros:kinetic-desktop-full

RUN apt-get update && apt-get install -y \
	    ros-kinetic-navigation \
       	    ros-kinetic-industrial-msgs \
            sudo \	    
	    curl \
	    wget \
	    nano \	    
	    unzip \			
	    && rm -rf /var/likb/apt/lists/*



